# Generated by Django 5.1.1 on 2024-10-15 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_announcement_sent_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerBenefits',
            fields=[
                ('benefit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('benefit', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.fertilizers')),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerNotes',
            fields=[
                ('notes_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=True)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.fertilizers')),
            ],
        ),
    ]
