# Generated by Django 5.1.1 on 2024-10-15 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_fertilizerbenefits_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesticideTargetPest',
            fields=[
                ('pest_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pest', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.pesticides')),
            ],
            options={
                'verbose_name_plural': 'Target Pests',
            },
        ),
    ]
